#DB
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: VtbBank123!
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: postgres

#Server
SERVER_PORT: 9000
ACTIVE_PROFILE: dev

#Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hahmedov20@gmail.com
EMAIL_PASSWORD: <app key>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}